# This file describes a Fastly Compute@Edge package. To learn more visit:
# https://developer.fastly.com/reference/fastly-toml/

authors = ["djiar@kth.se"]
description = "This is the tock function that will return to tick"
language = "javascript"
manifest_version = 2
name = "tock"
service_id = "7G7jkhdFKwL4f9XYQN3uBN"
